"""Base demo agent class.

``DemoAgent`` provides the common read → write loop.  Subclasses
override ``_content_for_step()`` to provide deterministic stub content.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

from agents.local.agent import LoomClient

logger = logging.getLogger(__name__)


@dataclass
class DemoAgentResult:
    """Result of a single demo agent's run."""

    agent_name: str
    agent_kind: str
    writes_count: int
    unit_ids: list[str] = field(default_factory=list)


class DemoAgent:
    """Base class for demo agents.

    Each agent reads the project context, then writes a chain of
    ``num_writes`` context units.  Content is generated by the
    ``_content_for_step()`` hook, which subclasses override.
    """

    def __init__(
        self,
        loom: LoomClient,
        agent_name: str,
        agent_kind: str,
        num_writes: int = 3,
    ) -> None:
        self._loom = loom
        self.agent_name = agent_name
        self.agent_kind = agent_kind
        self.num_writes = num_writes

    async def run(
        self,
        project_id: str,
        task_prompt: str,
    ) -> DemoAgentResult:
        """Execute the agent loop.

        1. Read existing context from the project.
        2. Write ``num_writes`` units, each as a child of the previous.
        3. Return the result summary.
        """
        # Read context first (for display / optional use by subclasses)
        context = await self._loom.read_context(
            project_id=project_id,
            task_description=task_prompt,
            budget=2048,
        )

        unit_ids: list[str] = []
        last_id: str | None = None

        for step in range(self.num_writes):
            content = self._content_for_step(step, task_prompt, context)
            version = step + 1  # Each write bumps version in its chain

            parent_ids = [last_id] if last_id else None
            parent_relations = ["derived_from"] if last_id else None

            result = await self._loom.write_context(
                project_id=project_id,
                content=content,
                version=version,
                type_="decision",
                parent_ids=parent_ids,
                parent_relations=parent_relations,
            )
            unit_id = result.get("id", str(step))
            unit_ids.append(unit_id)
            last_id = unit_id

            logger.info(
                "%s — wrote step %d/%d (id=%s)",
                self.agent_name,
                step + 1,
                self.num_writes,
                unit_id,
            )

        return DemoAgentResult(
            agent_name=self.agent_name,
            agent_kind=self.agent_kind,
            writes_count=self.num_writes,
            unit_ids=unit_ids,
        )

    def _content_for_step(
        self,
        step: int,
        task_prompt: str,
        context: list[dict],
    ) -> str:
        """Return deterministic stub content for the given step.

        Subclasses override this to shape content that exercises
        specific merge/conflict scenarios.
        """
        return f"{self.agent_name} — step {step + 1}: working on {task_prompt}"
